export const FEATURE_KEYS = [
  "settings",
  "students",
  "admission",
  "teachers",
  "academics",
  "attendance",
  "exams",
  "results",
  "fees",
  "sms",
  "notices",
  "payroll",
  "talent",
  "reports",
  "library",
  "transport",
  "hostel",
  "idCards",
  "certificates",
  "publicAdmission",
] as const;

export type FeatureKey = (typeof FEATURE_KEYS)[number];

export const DEFAULT_FEATURES: Record<FeatureKey, boolean> = {
  settings: true,
  students: true,
  admission: true,
  teachers: true,
  academics: true,
  attendance: true,
  exams: true,
  results: true,
  fees: true,
  sms: true,
  notices: true,
  payroll: true,
  talent: true,
  reports: true,
  library: true,
  transport: true,
  hostel: true,
  idCards: true,
  certificates: true,
  publicAdmission: true,
};

export const FEATURE_LABELS: Record<FeatureKey, string> = {
  settings: "Settings",
  students: "Students",
  admission: "Admission",
  teachers: "Teachers & Staff",
  academics: "Classes & Subjects",
  attendance: "Attendance",
  exams: "Exams",
  results: "Results",
  fees: "Fees",
  sms: "SMS",
  notices: "Notices",
  payroll: "Payroll",
  talent: "Talent tracking",
  reports: "Reports",
  library: "Library",
  transport: "Transport",
  hostel: "Hostel",
  idCards: "ID cards",
  certificates: "Certificates",
  publicAdmission: "Public admission",
};
