import { Router } from "express";
import { classRouter } from "../modules/Class/class.routes";
import { routineRouter } from "../modules/Routine/routine.routes";
import { subjectRouter } from "../modules/Subject/subject.routes";
import { attendanceRouter } from "../modules/Attendance/attendance.routes";
import { authRouter } from "../modules/Auth/auth.routes";
import { accountsRouter } from "../modules/Accounts/accounts.routes";
import { certificateRouter } from "../modules/Certificate/certificate.routes";
import { donationRouter } from "../modules/Donation/donation.routes";
import { examsRouter } from "../modules/Exam/exam.routes";
import { expenseRouter } from "../modules/Expense/expense.routes";
import { feesRouter } from "../modules/Fee/fee.routes";
import { hostelRouter } from "../modules/Hostel/hostel.routes";
import { libraryRouter } from "../modules/Library/library.routes";
import { noticeRouter } from "../modules/Notice/notice.routes";
import { ownerRouter } from "../modules/Owner/owner.routes";
import { payrollRouter } from "../modules/Payroll/payroll.routes";
import { publicRouter } from "../modules/Public/public.routes";
import { reportsRouter } from "../modules/Report/report.routes";
import { settingsRouter } from "../modules/Settings/settings.routes";
import { smsRouter } from "../modules/Sms/sms.routes";
import { staffAttendanceRouter } from "../modules/StaffAttendance/staffAttendance.routes";
import { studentsRouter } from "../modules/Student/student.routes";
import { teachersRouter } from "../modules/Teacher/teacher.routes";
import { transportRouter } from "../modules/Transport/transport.routes";
import { usersRouter } from "../modules/User/user.routes";

export const apiRouter = Router();

apiRouter.use(authRouter);
apiRouter.use(ownerRouter);
apiRouter.use(settingsRouter);
apiRouter.use(usersRouter);
apiRouter.use(classRouter);
apiRouter.use(subjectRouter);
apiRouter.use(routineRouter);
apiRouter.use(studentsRouter);
apiRouter.use(teachersRouter);
apiRouter.use(attendanceRouter);
apiRouter.use(staffAttendanceRouter);
apiRouter.use(examsRouter);
apiRouter.use(certificateRouter);
apiRouter.use(feesRouter);
apiRouter.use(expenseRouter);
apiRouter.use(donationRouter);
apiRouter.use(accountsRouter);
apiRouter.use(noticeRouter);
apiRouter.use(smsRouter);
apiRouter.use(payrollRouter);
apiRouter.use(libraryRouter);
apiRouter.use(transportRouter);
apiRouter.use(hostelRouter);
apiRouter.use(reportsRouter);
apiRouter.use(publicRouter);
